name: ecomm_store_app
description: "A new Flutter project."
 
 
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ^3.9.2

 
 #--------------------PACKAGES / DEPENDENCIES--------------------#
dependencies:
  flutter:
    sdk: flutter

  #---------Utility Packages---------#
  http: ^1.6.0
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # ICONS
  iconsax: ^0.0.8 
  cupertino_icons: ^1.0.8


  # STATE MANAGEMENT
  get: ^4.7.3
  get_storage: ^2.1.1


  # Product Specific



#-----------PACKAGES END-----------#


#---- Development Dependencies ----#
dev_dependencies:
  flutter_test:
    sdk: flutter

     
  flutter_lints: ^6.0.0

 

flutter:  
  uses-material-design: true


  #---- local ASSETS ----# 
  assets:
    # - assets/images/shoe_1.png
    # - assets/images/shoe_2.png
    # - assets/images/shoe_3.png
    # - assets/images/shoe_4.png
    # - assets/images/shoe_5.png
    # - assets/images/shoe_6.png
    - assets/images/onboarding_images/
    - assets/images/banners/
    - assets/images/animations/
    - assets/images/products/
    - assets/logos/
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/icons/payment_methods/
    - assets/images/user

   
   #---- local Fonts ----# 
   
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost/static/Jost-Light.ttf
          weight: 300
        - asset: assets/fonts/Jost/static/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost/static/Jost-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Jost/static/Jost-Medium.ttf
          weight: 500   
        - asset: assets/fonts/Jost/static/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost/static/Jost-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Jost/static/Jost-SemiBold.ttf
          weight: 600
   
   
   
   
   
   
   
   
